### PR TITLE
TECH-197: [wp-curate] Unvalidated GLOBAL variable throws warning when not set

### LINKED ISSUE #386: Unvalidated GLOBAL variable throws warning when not set
### Description of the bug

`PHP message: Warning: Undefined global variable $parsely in /var/www/wp-content/plugins/wp-curate/src/features/class-parsely-support.php on line 63`

A lower environment that has WP-Curate installed is flooding the runtime logs with the above message. This variable and others in the file should be validated before being accessed.

### Steps To Reproduce

See above.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by jakewrfoster**
## Summary

[wp-curate] Unvalidated GLOBAL variable throws warning when not set

## Notes for reviewers

None.

## Ticket(s)

- [TECH-197](https://alleyinteractive.atlassian.net/browse/TECH-197)

[TECH-197]: https://alleyinteractive.atlassian.net/browse/TECH-197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: src/features/class-parsely-support.php [hunk 1]
```diff
@@ -45,8 +45,8 @@ public function boot(): void {
 	 * @return array<number> Array of post IDs.
 	 */
 	public function add_parsely_trending_posts_query( array $posts, array $args ): array {
-		$parsely = $GLOBALS['parsely'];
-		if ( ! $parsely->api_secret_is_set() ) {
+		$parsely = $GLOBALS['parsely'] ?? null;
```
Comment (dlh01) [inline src/features/class-parsely-support.php]: I kind of like `global $parsely;` for these because it gives you null-coalescing for free.

**Review by dlh01 — APPROVED** [review]
🌳

File: src/features/class-parsely-support.php [hunk 2]
```diff
@@ -45,8 +45,8 @@ public function boot(): void {
...
+		if ( is_null( $parsely ) || ! $parsely->api_secret_is_set() ) {
```
Comment (srtfisher) [inline src/features/class-parsely-support.php]: could do an instanceof check to be extra sure and get the type checking included

File: src/features/class-parsely-support.php [hunk 3]
```diff
@@ -60,7 +61,7 @@ public function add_parsely_trending_posts_query( array $posts, array $args ): a
 	 * @return array<int> An array of post IDs.
 	 */
 	public function get_trending_posts( array $args ): array {
-		$parsely = $GLOBALS['parsely'];
+		global $parsely;
```
Comment (srtfisher) [inline src/features/class-parsely-support.php:64]: worth adding an instanceof here, too?

**Review by srtfisher — APPROVED** [review]

File: src/features/class-parsely-support.php [hunk 4]
```diff
@@ -45,8 +45,9 @@ public function boot(): void {
 	 * @return array<number> Array of post IDs.
 	 */
 	public function add_parsely_trending_posts_query( array $posts, array $args ): array {
-		$parsely = $GLOBALS['parsely'];
-		if ( ! $parsely->api_secret_is_set() ) {
+		global $parsely;
+
+		if ( ! class_exists( '\Parsely\Parsely' ) || empty( $parsely ) || ! $parsely instanceof Parsely || ! $parsely->api_secret_is_set() ) {
```
Comment (dlh01) [inline src/features/class-parsely-support.php:50]: I think `$parsely instanceof Parsely` implies the first two checks.

```suggestion
		if ( ! $parsely instanceof Parsely || ! $parsely->api_secret_is_set() ) {
```

**Review by dlh01 — APPROVED** [review]
🌳

File: src/features/class-parsely-support.php (hunk 4 above)
Comment (jakewrfoster) [reply src/features/class-parsely-support.php:50]: this suggestion makes PHPStan angry. instead of ignoring the line, I added additional checks to appease.
